# Generated by Django 4.2.5 on 2023-10-02 08:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("service", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cook",
            name="year_of_experience",
            field=models.IntegerField(null=True),
        ),
    ]
