# Generated by Django 4.2.5 on 2023-10-02 16:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("service", "0003_alter_ingredient_unit"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cook",
            name="year_of_experience",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
