# Generated by Django 4.2.5 on 2023-10-09 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("service", "0005_alter_cook_year_of_experience"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dish",
            name="ingredients",
        ),
        migrations.AddField(
            model_name="ingredient",
            name="dish",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="dishes",
                to="service.dish",
            ),
            preserve_default=False,
        ),
    ]
