# Generated by Django 4.2.5 on 2023-10-10 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("service", "0006_remove_dish_ingredients_ingredient_dish"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ingredient",
            name="dish",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ingredients",
                to="service.dish",
            ),
        ),
    ]
